### ISSUE TITLE
docker image

### ISSUE THREAD

**Issue by arnitolog** [papirosko/mm2-lag#1]
Hi,

do you happen to have the docker image in any registry?

**Comment by papirosko** [comment]
nothing in public, only our private gitlab.

**Comment by arnitolog** [comment]
got it. will try to build my own.
thanks a lot for the tool!

пн, 15 квіт. 2024 р. о 11:34 Vladimir Penkov ***@***.***>
пише:

**Comment by papirosko** [comment]
@arnitolog please try 

```
docker run papirosko/mm2-lag
```

**Comment by arnitolog** [comment]
yeah, that works. thanks
